version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql

  sqli_vuln_demo:
    container_name: sqli_vuln_demo
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development
    
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8051:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sqli_vuln_demo